openapi: 3.0.3
info:
  title: STD24176
  description: This is a specification of STD24176
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'

components:
  parameters:
    IdParam:
      name: id
      description: The id of the phone
      in: path
      required: true
      schema:
        type: string

  schemas:
    Characteristic:
      description: The characteristics of the phone
      type: object
      properties:
        ram_memory:
          type: number
        rom_memory:
          type: number
paths:
  
