openapi: 3.0.3
info:
  title: STD24176
  description: This is a specification of STD24176
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'

components:
  parameters:
    IdParam:
      name: id
      description: The id of the phone
      in: path
      required: true
      schema:
        type: string

  schemas:
    Characteristic:
      description: The characteristics of the phone
      type: object
      properties:
        ram_memory:
          type: number
        rom_memory:
          type: number

    Phone:
      description: The phone
      allOf:
        - type: object
          properties:
            identifier:
              type: string
            brand:
              type: string
            model:
              type: string
        - $ref: "#/components/schemas/Characteristic"

paths:
  /health:
    get:
      responses:
        "200":
          description: Get health of the server
          content:
            text/plain:
              schema:
                type: string
              example: Ok

  /phones:
    post:
      summary: Adding a new phone
      requestBody:
        description: The informations of the new phone
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Phone"
      responses:
        "201":
          description: The phone was well created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: The phone created successfully

    get:
      summary: Get all the phones
      responses:
        "200":
          description: Return the full list of phones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Phone"

  /phones/{id}:
    get:
      summary: Get a single phone by its id
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Return the wanted phone
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"
        "404":
          description: The wanted phone was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: The phone was not found or does not exist





